# Hunt the Wumpus {#hunt-the-wumpus}

Today we will program  a text adventure computer game [Hunt the Wumpus](https://en.wikipedia.org/wiki/Hunt_the_Wumpus): "In the game, the player moves through a series of connected caves, arranged in a dodecahedron, as they hunt a monster named the Wumpus. The turn-based game has the player trying to avoid fatal bottomless pits and "super bats" that will move them around the cave system; the goal is to fire one of their "crooked arrows" through the caves to kill the Wumpus..."

As before, we will start with a very basic program and will build it step-by-step towards the final version. The purpose of this chapter is to consolidate the skills you already have by using them in a more complex game with multiple functions, game objects, etc. Do not forget to comment the entire file (top multiline comment to explain what this will be about), structure your code, comment individual chunks, and use sensible variable and function names. Your code complexity will be pretty high, so you will need the good style to help you with it.

## Chapter concepts
* Using [sets](#sets).

## A system of caves
In our game, the player will wander through a systems of caves with each cave being connected to three other caves. The cave layout will be a _CONSTANT_, so we will define at the beginning of the program as follows.
```{python eval = FALSE}
CONNECTED_CAVES = [[1, 4, 5], [2, 0, 7], [3, 1, 9], [4, 2, 11], 
                   [0, 3, 13], [6, 14, 0], [7, 5, 15], [8, 6, 1], 
                   [9, 7, 16], [10, 8, 2], [11, 9, 17], [12, 10, 3], 
                   [13, 11, 18], [14, 12, 4], [5, 13, 19], [16, 19, 6], 
                   [17, 15, 8], [18, 16, 10], [19, 17, 12], [15, 18, 14]]
```

Let us decipher this. You have a list of twenty elements (caves). Inside each element is a list of connected caves (caves you can travel to). This means, that if you are in cave #1 (index `0`), it is connected to  `CONNECTED_CAVES[0]` → `[1, 4, 5]` (note that these numbers inside are zero-based indexes as well!). So, to see what is the index of the second cave connected to the first one you would write `CONNECTED_CAVES[0][1]` (you get first element of the list and, then, the second element of the list from inside).

To allow the player to wander, we need to know where they are to begin with. Let us define a new variable called, simply, `player_location` and assign a random integer with a _valid_ cave index. Think about the lowest valid index you can have in Python (this you need to hardcode). To compute the highest possible valid index, you need to know the total number of the caves, i.e., length --- [len()](https://docs.python.org/3/library/functions.html#len) --- of the list. Remember, the indexes in Python are zero-based, so think how to compute highest valid index from the length! Use these two indexes and put the player into a random cave. For this, you can use [randint](https://docs.python.org/3/library/random.html#random.randint) function. Look at previous chapters, if you forgot how to use it. 

Our player needs to know where they can go, so on each turn we will need to print out the information about which cave the player is in and about the connecting cave (use [string formatting](#string-formatting) to make this look nice). Let this be our first code snippet for the game. The code should look like this
```{python eval=FALSE}
# import randint

# define CONNECTED_CAVES (simply copy-paste the definition)

# create `player_location` variable and set it to a random valid index 
# putting player into a random cave

# print out the current cave index and indexes of the connected caves. Use string formatting.
```

::: {.program}
Put your code into _code01.py_.
:::

## Wandering around
Now that the player can "see" where they are, let them wander! Use `input()` function to ask for the index of the cave the player wants to go to and "move" the player to that cave (which variable do you need to modify?). Remember that `input()` returns a string, so you will need to explicitly convert it to an integer (see [Guess-the-Number](#guess-the-number-single-round) game, if you forgot how to do it). For now, enter only valid numbers, as we will add checks later. To make wandering continuous, put it inside the [while loop](#while-loop), so that player wanders until they get to the cave #5 (index `4`!). We will have more sensible game-over conditions later on but this will allow you to exit the game without interrupting it from outside. The code should look like this (remember to watch your indentations!).

```{python eval=FALSE}
# import randint function

# define CONNECTED_CAVES (simply copy-paste the definition)

# create `player_location` variable and set it to a random valid cave index

# while player is not in the cave #5 (index 4):
    # print out the current location and list of the connected caves. Use string formatting.
    # get input about the cave the player want to go to and "move" the player
    
# print a nice game-over message
```

::: {.program}
Put your code into _code02.py_.
:::

## Checking whether a value is _in_ the list[#in-collection]
Right now we trust the player (well, you) to enter the correct index for the cave. Thus, the program will move a player to a new cave even if you enter an index of the cave that is not connected to the current one. Even worse, it will try to move the player to an undefined cave, if you enter an index larger than 19. To check whether an entered index matches one of the connected cave, you need to use [<value> in <list>](https://docs.python.org/3/tutorial/datastructures.html#more-on-conditions) conditional statement. The idea is straightforward, if the value is in the list, the statement is `True`, if not, it is `False`. 

```{python}
x = [1, 2, 3]
print(1 in x)
print(4 in x)
```

Note that you can check _one_ value/object at a time. Because a list is also a single object, you will be checking whether it is an element of the other list, not whether all or some of it elements are in it.

```{python}
x = [1, 2, [3, 4]]
# This is False because x has no element [1, 2], only 1, and 2 (separately)
print([1, 2] in x)

# This is True because x has [3, 4] element
print([3, 4] in x)
```

::: {.practice}
Do exercise #1.
:::

## Checking valid cave index
Now that you know how to check whether a value is in the list, let's use it to validate cave index. Before moving the player, you now need to check whether the entered index is in the list of the connected caves. If this is `True`, you move the player as before. Otherwise, print out an error message, e.g. "Wrong cave index!" without moving a player. Loop will ensure that the player will be prompted for the input again, so we don't need to worry about this for the moment. Here, you will need to create a temporary variable to store the player's input as you need to check it validity _before_ you decide whether you move the player. You only do the latter, if the value in that temporary variable is an index of one of the connected caves! 

Modify your code to include input-validity check.

::: {.program}
Put your code into _code03.py_.
:::

## Checking that string can be converted to an integer
There is another danger with out input: The player is not guaranteed to enter a valid integer! So far we relied on you to behave but in real life, even when people do not deliberately try to break your program, they will occasionally press the wrong button. Thus, we need to check that the _string_ that they entered can be converted to an _integer_.

Python string is an object (more on that in a few chapters) with different methods that allow to perform various operations on them. One subset of methods allows you to make a rough check of its content. The one we are interested is [str.isdigit()](https://docs.python.org/3/library/stdtypes.html#str.isdigit) that checks whether all symbols are digits and that the string is not empty (it has at least one symbol). You can follow the link above to check other alternatives such as `str.islower()`, `str.isalpha()`, etc.

::: {.practice}
Do exercise #2.
:::

## Checking valid integer input
Modify the code that gets the input from the user. First, store the raw string (not converted to an integer!) into an intermediate variable. Then, if that string is all digits, convert it to an integer, and then do the check that it is a valid connected cave index (moving player or printing an error message). However, if input string is not all digits, only print the error message ("Invalid cave index!"). This means you need to have an if-statement inside the if-statement!

::: {.program}
Put your code into _code04.py_.
:::

## Encapsulating the code in a function
Your code has already grown in complexity with two checks on top of an input function, so it makes sense to hide this complexity by encapsulating it in a function. Let us call it `input_cave`, as it will an input for valid index of a connected cave only. You already have all the code you need, but think which parameter (or parameters?) it requires: you _cannot_ access the global constant `CONNECTED_CAVES` or the global variable `player_location` directly!


Put the function in a separate `utils.py` file, document both the file and the function! Import and use it in the main script. Your program should run _exactly_ as before!

::: {.program}
Put `input_cave` into _utils.py_.
<br/>
Update your code in _code05.py_.
:::

## Sets {#sets}

So far, we had only the player to keep the track of and we were doing it by storing their location in the `player_location` variable. However, as we will add more game objects (bottomless pits, bats, the Wumpus), we need to keep the track of who-is-where, so that we don't place them in an already occupied cave. We will use this as an opportunity to learn about [sets](https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset): an _unordered_ collection of _unique_ elements. These are an implementation of [mathematical sets](https://en.wikipedia.org/wiki/Set_(mathematics)) and have properties useful for our required bookkeeping. You create a set via [set()](https://docs.python.org/3/library/stdtypes.html#set) function and it can be either an empty set (to which you can `.add()`) or it can convert a list (or a tuple) into a set but it will drop all duplicates.

```{python}
# starting from an empty set
a_set = set()
a_set.add(1)
print(a_set)
a_set.intersection()

# converting a list to a set
print(set([1, 2, 2, 3]))
```

If you have two sets, you can perform various operations to find [union](https://docs.python.org/3/library/stdtypes.html#frozenset.union), [intersection](https://docs.python.org/3/library/stdtypes.html#frozenset.intersection), or [difference](https://docs.python.org/3/library/stdtypes.html#frozenset.difference) between two sets (see _Basic operations_ in the [wikipedia](https://en.wikipedia.org/wiki/Set_(mathematics)).

::: {.practice}
Do exercise #3.
:::

Note that the set is _unordered_, so you cannot access its individual elements. However, you can check whether a value is [in](#in-collection) the set the same way you do with lists
```{python}
a_set = set([1, 2, 3, 3])
3 in a_set
```


## Keeping track of occupied caves
Now that you know about sets, keeping track of occupied caves will be easy. In the global script, we need a variable that will hold indexes of all occupied caves in a [set](#sets) (you start with an empty set, as all caves are initially vacant). We also need a function that will generate a valid index of a vacant cave base on 1) range of valid indexes (think what is the most economic way to pass this information to the function, you can get away with just one integer) and 2) indexes of already occupied caves (we have it in the global variable that you define but, again, you _cannot_ access that variable directly, so you _must_ pass this information as a parameter!). 

We will write this function twice. First, we will use a brute force method to find a vacant cave: just generate a valid random index in a loop until it is _not_ in the set of occupied caves. Since it is not, this is a valid vacant cave, so you should exit the loop and return this value. Call this function `find_vacant_cave_bruteforce`, implement and document it in `utils.py`, test it by copying it into a Jupiter notebook and running it multiple times with various hard coded sets of occupied caves. Check that the valid cave is never in the occupied caves set.

::: {.program}
Put `find_vacant_cave_bruteforce` into _utils.py_.
<br/>
Test it in exercise 4.
:::

The function you wrote works, but it is very inefficient and can be quite problematic if our set of occupied caves is long, as you will need many attempts before you _randomly_ find a vacant one. We can do better than this by using set operations as we can generate [range](https://docs.python.org/3/library/functions.html#func-range), turn it into a set, [subtract](https://docs.python.org/3/tutorial/datastructures.html#sets) occupied caves from it (that leaves a set of unoccupied caves), and then [choose](https://docs.python.org/3/library/random.html#random.choice) one value (but note that you need to convert a set to a [list](https://docs.python.org/3/library/stdtypes.html#list) for this!). In the last step, we are choosing randomly but _only_ from vacant caves, so we do not need loops and multiple attempts to get it right.

Implement `find_vacant_cave` function and test it using the same code as before. You should always get only a valid vacant cave index.

::: {.program}
Put `find_vacant_cave` into _utils.py_.
<br/>
Test it in exercise 5.
:::

## Placing bottomless pits
Now that we have the scaffolding in place, let us add bottomless pits. The idea is simple, we place two of those in random _vacant_ caves, so when the player wanders into a cave with a bottomless pit, they fall down and die (game over). We will, however, warn the player, that their current cave is next to a bottomless pit, without telling them which cave it is in specifically. 

First thing first, let us add them. For this, we will create a new constant `NUMBER_OF_BOTTOMLESS_PITS` (I suggest that we set it to `2` but you can have more or fewer of them) and a new variable (`bottomless_pits`) that will hold a set of indexes of caves with the bottomless pits in them. Add bottomless pits to using using a for loop: On each iteration get an index of an empty cave (via `find_empty_cave` function think about its parameters), add this index to both 1) `bottomless_pits` and 2) `occupied_caves` variables, so that you 1) know where bottomless pits are and 2) know which caves are occupied. Here is the code outline for the initialization part (do not copy paste the main loop just yet). See if numbers makes sense (number of caves is what you expected them to be, value are within the range, there are no duplicates, etc.)

```python
# create `occupied_caves` variable and initialize it to an empty set
# create `bottomless_pits` variable and initialize it to an empty set
# use for loop and range function to repeat the for loop NUMBER_OF_BOTTOMLESS_PITS times
#     generate a new location for the bottomless pit via find_empty_cave() function and add it to both sets
```

::: {.program}
Test code for creating bottomless pits <br/> in exercise 6.
:::

## Falling into a bottomless pit
Now we will add one of the ways for the game to be over: the player falls into a bottomless pit. For this, we just need to check whether player is currently in a cave that has a bottomless pit in on every turn. If that is the case, player's cave is indeed in the bottomless pits list, print a sad game over message and `break` out of the loop. In addition, let us modify the `while` loop condition to `while True:`, so that the only way to end the game is to fall into the pit (not exactly fair to the player, but we'll fix that later).

Put the code for placing bottomless pits and falling into them into the main script. Print out the bottomless pits caves at the start of the program and wonder into them to make sure that this will correctly end the game.

::: {.program}
Update your code in _code06.py_.
:::

## Warning about a bottomless pit
We need to give the player a chance to avoid the fate of falling into a bottomless pit but warning him that one (or two, or more) are nearby. To this end, we need to print additional information _before_ they decide to make their move. Your task is to check whether there is a cave that is both in `bottomless_pits` set and current connected caves list. You can use a [for loop](#for-loop) but using set operations is much easier, you just need to check whether an [intersection](https://docs.python.org/3/library/stdtypes.html#frozenset.intersection) of there two sets is empty (it has zero [length](https://docs.python.org/3/library/functions.html#len)). If at least one of the connected caves has a bottomless pit in it, print "You feel a breeze!".

::: {.program}
Put your code into _code07.py_.
:::

## Placing bats and warning about them
We need more thrills! Let us add bats to the fray. They live in caves, the player can hear them, if they are in a connect cave ("You hear flapping!"), but if the player inadvertently enters the cave with bats, they carry the player to a _random_ cave. 

Placing the bats is analogous to placing bottomless pits. You need a constant that determines the number of bat colonies (e.g., `NUMBER_OF_BATS` and set it `2` or some other number you prefer), a variable that holds a set with indexes of caves with bats (e.g., `bats`), and you need to pick random empty caves and store them in `bats` in exactly the same way you did it with bottomless pits. Print out location of bats for diagnostic purposes. 

For warning about the bats, it is also the same logic as for bottomless pits: If one of the connected caves have bats in them, you print out `"You hear flapping!"`.

::: {.program}
Put your code into _code08.py_.
:::


## Player gets transported by bats to a random cave
If the player is in the cave with bats, they transport them to a _random_ cave, _irrespective_ of whether the cave is occupied or not (so, any cave is a valid cave). Thus, bats can carry the player to a cave:

1. with another bat colony and it will transport the player again.
2. with a bottomless pit and the player will fall into it.
3. later on, to the cave with the Wumpus (the player may not survive that one and you don't implement this now).

Think about:

1. _when_ you check for bats presence (before or after checking for a bottomless pit?),
2. do you check once (using `if`) or one-or-more times (using `while`)

Test your code by walking into a cave with bats (print their location at the start, so you know where to go).

::: {.program}
Put your code into _code09.py_.
:::

## Adding Wumpus (and getting eaten by it).
By now you have added a player (single, location stored as in integer), bottomless pits (plural, locations stored in a set), and bats (plural as well). Add Wumpus!

1. Create a new variable (`wumpus`?) and place Wumpus in a vacant cave. Print out location of Wumpus for debugging purposes.
2. Warn about Wumpus in the same code that warns about pits and bats. Logic is the same but the check is simpler as you have just a single Wumpus location to worry about. Canonical warning text is `"You smell a Wumpus!"`. 
3. Check if player is in the same cave as Wumpus. If that is the case, game is over, as the player is eaten by a hungry Wumpus. This is similar to _game-over_ due to falling into a bottomless pit. Think about whether the check should before or after check for bats.

Test your code by walking into a cave with Wumpus (print their location at the start, so you know where to go).

::: {.program}
Put your code into _code10.py_.
:::

## Giving player a chance.
Let us give player a chance. As they enter the cave with the Wumpus, they startle it. Then, Wumpus either runs away to a random adjacent cave (new) or stays put and eats the player. First, create a new constant that defines a probability that Wumpus runs away, e.g. `P_WUMPUS_SCARED`. In implementations I've found, it is typically 0.25, but use any value you feel is reasonable.

Thus, if the player is in the cave with Wumpus, draw a random number between 0 and 1 (use [uniform](https://docs.python.org/3/library/random.html#random.uniform) function for that). It is part of [random](https://docs.python.org/3/library/random.html) library, so the call is `random.uniform(...)`. Remember that you can either import the _entire_ library and then call its function by prefixing them with the library name or you can import only a specific function via `from ... import ...`. Once you generated the number between 0 and 1, if that number is _smaller_ than probability that the Wumpus is scared, move it to a random adjacent cave (bats ignore Wumpus and it clings to the ceiling of the caves, so bottomless pits are not a problem for it). A useful function that you already used is [choice()](https://docs.python.org/3/library/random.html#random.choice), again, part of [random](https://docs.python.org/3/library/random.html) library. Otherwise, if Wumpus was not scared off, the player is eaten and game is over (the only outcome in _code10_).

::: {.program}
Put your code into _code11.py_.
:::

## Flight of a crooked arrow
Our player is armed with _crooked_ arrows that can fly through caves. The rules for its flight are the following:

* The player decide in which cave it shoots an arrow and how far the arrow flies (from 1 up to 5 caves).
* Every time the arrow needs to flight into a next cave, that cave is picked randomly from adjacent caves _excluding_ the cave it came from (so, the arrow cannot make a 180° turn and there are only two out of three caves available for choosing).
* If the arrow flies into a cave with Wumpus, it is defeated and the game is won.
* If the arrow flies into a cave with the player, then they committed unintentional suicide and the game is lost.
* If the arrow reached its last cave (based on how far the player wanted to shoot) and the cave is empty, it drops down on the floor.
* Bats or bottomless pits have no effect on the arrow.

The total number of arrows the player has at the beginning should be defined in `ARROWS_NUMBER` constant (e.g., `5`).

To keep track of the arrow, you will need following variables:

* `arrow`: current location of the arrow.
* `arrow_previous_cave`: index of the cave the arrow came from, so that you know where it cannot flight back.
* `remaining_shooting_distance`: remaining distance to travel.
* `remaining_arrows`: number of remaining arrows (set to `ARROWS_NUMBER` when the game starts).

Keep this scaffolding in mind and lets start programming our arrows.


## Random cave but no U-turn
You need to program a function (call it `next_arrow_cave()`) that picks a random cave but not the previous cave the arrow had been in. It should have two parameters:

* `connected_caves`: a list of connected caves.
* `previous_cave`: cave from which the arrow came from.

First, debug the code in a separate cell. Assume that `connected_caves = CONNECTED_CAVES[1]` (so, arrow is currently in cave 1) and `previous_cave = 0` (arrow came from cave 0). Write the code that will pick one of the remaining caves randomly (in this case, either `2` or `7`), you probably want to use set operations (as with placing game objects efficiently). Once the code works, turn it into a function that returns the next cave for an arrow. Document the function. Test it with for other combinations of connected and previous caves.

::: {.program}
Test your code in exercise #7.<br/>
Once tested, put function into _utils.py_.
:::

## Going distance
Now that you have a function that flies to the next random cave, implement flying using a for loop. An arrow should fly through `shooting_distance` caves (set it to `5`, maximal distance, by hand for testing). The _first_ cave is given (it will be picked by the player), so set `arrow` to `1` and `arrow_previous_cave` to `0` (player is in the cave `0` and shot the arrow into cave `1`). For debugging purposes, print out location of the arrow on each iteration. Test the code by changing `shooting_distance`. In particular, set it to `1`. The arrow should "fall down" already in cave `1`.

For this, used a stripped down version of the code with `CONNECTED_CAVES` constant, the imported `next_arrow_cave()` function, and all the relevant constants and variables for the arrow. Hard code initial cave, previous cave, and distance by hand.

::: {.program}
Put your code into _code12.py_.
:::

## Hitting a target
Implement check for hitting the Wumpus or the player in the loop. Should the check be before or after the arrow flies to the next random cave? In both cases, write an appropriate "game over" message and break out of the loop. Test the code by placing Wumpus by hand into the cave the player is shooting at or the next one. 

You can build on the code from the previous section but add `player_location` and `wumpus` variables hard coding them by hand for debugging. Run code multiple times to check that it works.

::: {.program}
Put your code into _code13.py_.
:::

## Move or shoot?
We are almost where but before we can start putting the code together we need a few more things. For example, previously the player could only move, so we just asked for the next cave number. Now, on each turn, the player will have a choice of shooting an arrow or moving. Implement a function `input_shoot_or_move()` that has no parameters and returns `"s"` for shooting o `"m"` for moving. Inside, ask the player about their choice until they pick one of two valid options. Conceptually, this is very similar to your other input function `input_cave()` that repeatedly requests input until a valid one is given. Test and document!

::: {.infobox .program}
Put `input_shoot_or_move()` into _utils.py_<br/>Test it in exercise 8.
:::

## How far?
Implement `input_distance()` function that has no parameters and returns the desired shooting distance between `1` and `5`. Again, repeatedly ask for an _integer_ number input (remember, you know how to check whether input is a valid integer) on how far the arrow should travel until valid input is given. This is very similar to your other input functions. Test and document.

::: {.infobox .program}
Put `input_distance()` into _utils.py_<br/>Test it in  exercise 9.
:::

## input_cave_with_prompt
Create a new version of the `input_cave()` function called `input_cave_with_prompt` and add `prompt` parameter to it, so now we can ask either about moving to or shooting at the cave (hence, the need for the prompt in place of a hard-coded message).

::: {.infobox .program}
Put `input_cave_with_prompt()` into _utils.py_<br/>Test it in  exercise 10.
:::

## Putting it all together
In the last few section, you have created all the bits and pieces that you need for the final game with a crooked arrow. Here is a pseudocode for how the final code should look like. Take a look to better understand how the new bits get integrated into the old code. By now, you should have following constants (you can have other values):

* `CONNECTED_CAVES`
* `NUMBER_OF_BATS` = 2
* `NUMBER_OF_BOTTOMLESS_PITS` = 2
* `P_WUMPUS_SCARED` = 0.25
* `ARROWS_NUMBER` = 5

Following functions:

* `find_vacant_cave(...)`, returns an integer cave index
* `input_cave_with_prompt(prompt, connected_cave)`, returns an integer cave index
* `input_shoot_or_move()`, returns `"s"` for shoot and `"m"` for move.
* `input_distance()`, returns an integer between 1 and 5
* `next_arrow_cave(connected_caves, previous_cave)`, return an integer cave index

Following variables:

* `player_location` : cave index
* `bottomless_pit`: list of cave indexes
* `bats`: list of cave indexes
* `wumpus`: cave index
* `remaining_arrows`: integer number of remaining arrows

Service/temporary variables:

* `occupied_caves`: list of cave indexes
* `gameover_due_to_arrow` : indicates whether game is over because either Wumpus or player was hit by an arrow
* `arrow`: location of an arrow initially based on the player's choice
* `shooting_distance`: number of caves the arrow should fly through.
* other arrow related temporary variables

```
import libraries that you need

import functions that you need from utils

define CONSTANTS

place player, bottomless pits, bats, and wumpus
set number of remaining arrows to ARROWS_NUMBER
set gameover_due_to_arrow variable to False

while TRUE:
    while player wants to shoot and has arrows:
        ask about cave that player want to shoot at  (store answer in `arrow` variable)
        ask how the far the arrow should fly (store answer in `shooting_distance` variable)
        
        fly arrow through caves in for loop:
            if hit wumpus -> congrats game over message, gameover_due_to_arrow = True, and break out of the loop
            if hit player -> oops game over message, gameover_due_to_arrow = True, and break out of the loop
            move arrow to the next random cave (next_arrow_cave function and arrow variable)
        decrease number of remaining arrows (remaining_arrows variable)
        
    check if game is over due to arrow, break out of the loop, if that is the case
        
    ask player about the cave he want to go to and move player
    
    while player is in the cave with bats: 
        move player to a random cave
    
    check for bottomless pits (player dies, break out of the loop)
    
    if player is in the same cave as wumpus:
        if wumpus is scared
            move wumpus to a random cave
        otherwise
            player is dead, break out of the loop
```

::: {.infobox .program}
Put your code into _code14.py_.
:::

## Wrap up
Well done, that was a real adventure exploring these caves! Zip and submit.
